import Head from 'next/head'

import Hero from '../components/hero/hero'
import About from '../components/about/about'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Filterman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <About />
      </main>
    </>
  )
}
